<a href="https://colab.research.google.com/github/sushgho/Msc-Project/blob/sushgho-patch-1/gibots_com_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn import tree
import pydotplus
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import matplotlib.image as pltimg
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO 
from IPython.display import Image 
from pydot import graph_from_dot_data
import numpy as np

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)

In [2]:
X=pd.read_csv('train.csv')
X

        id   x1   x2  ... x143      x144      x145
0        1   NO   NO  ...    2  0.375535  0.464610
1        2  NaN  NaN  ...    4  0.741682  0.593630
2        3   NO   NO  ...    1  0.776467  0.493159
3        4  YES   NO  ...    3  0.168234  0.546582
4        5   NO   NO  ...    1  0.246637  0.361045
...    ...  ...  ...  ...  ...       ...       ...
9994  9995   NO   NO  ...    1  0.502268  0.486637
9995  9996   NO   NO  ...   15  0.890135  0.346276
9996  9997  YES  YES  ...    5  0.726457  0.659001
9997  9998   NO   NO  ...    3  0.450980  0.561448
9998  9999  YES  YES  ...    0  0.604274  0.499395

[9999 rows x 146 columns]

In [3]:
X=X.applymap(str)

In [4]:
from sklearn import preprocessing
X=X.apply(preprocessing.LabelEncoder().fit_transform)
X

        id  x1  x2    x3   x4    x5  ...  x140  x141  x142  x143  x144  x145
0        0   0   0  3093  225   721  ...     1     0     1    21  1830  2935
1     1111   2   2  3814  627     0  ...     1     0     1    46  3706  3893
2     2222   0   0  3421  447  2666  ...     0     0     0     1  3897  3151
3     3333   1   0  1008  458   967  ...     0     0     1    35   557  3562
4     4444   0   0  2125   74  2884  ...     0     0     0     1  1069  2008
...    ...  ..  ..   ...  ...   ...  ...   ...   ...   ...   ...   ...   ...
9994  9994   0   0  3476  281  2235  ...     1     0     1     1  2459  3104
9995  9995   0   0  1996  467  2880  ...     1     0     1    11  4507  1906
9996  9996   1   1   810  438  2877  ...     1     0     1    53  3616  4299
9997  9997   0   0   871  559  2505  ...     0     0     0    35  2206  3676
9998  9998   1   1  1736  467   999  ...     1     0     1     0  2970  3198

[9999 rows x 146 columns]

In [5]:
y=pd.read_csv('trainLabels.csv')
y

          id  y1  y2  y3  y4  y5  y6  ...  y27  y28  y29  y30  y31  y32  y33
0          1   0   0   0   0   0   0  ...    0    0    0    0    0    0    1
1          2   0   0   0   0   0   0  ...    0    0    0    0    0    1    0
2          3   0   0   1   0   0   0  ...    0    0    0    0    0    0    0
3          4   0   0   0   0   0   0  ...    0    0    0    0    0    0    1
4          5   0   0   0   0   0   0  ...    0    0    0    0    0    0    1
...      ...  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...
49994  49995   0   0   0   0   0   0  ...    0    0    0    0    0    0    1
49995  49996   0   0   0   0   0   0  ...    0    0    0    0    0    0    1
49996  49997   0   0   0   0   0   0  ...    0    0    0    0    0    0    1
49997  49998   0   0   0   0   0   0  ...    0    0    0    0    0    0    1
49998  49999   0   0   0   0   0   1  ...    0    0    0    0    0    0    0

[49999 rows x 34 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X[:5000], y[:5000], random_state=1)

In [7]:
dt = DecisionTreeClassifier()
clf=dt.fit(X_train, y_train)
clf

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [8]:
from sklearn.metrics import accuracy_score

In [9]:
predictions = dt.predict(X_test)
predictions

array([[4455,    0,    0, ...,    0,    0,    0],
       [2167,    0,    0, ...,    0,    0,    1],
       [3394,    0,    0, ...,    0,    0,    1],
       ...,
       [3498,    0,    0, ...,    0,    0,    1],
       [ 578,    0,    0, ...,    0,    0,    1],
       [1089,    0,    0, ...,    0,    0,    1]])

In [10]:
z=pd.read_csv('sampleSubmission_small.csv')
z

        id_label  pred
0     1700001_y1     0
1     1700001_y2     0
2     1700001_y3     0
3     1700001_y4     0
4     1700001_y5     0
..           ...   ...
985  1700030_y29     0
986  1700030_y30     0
987  1700030_y31     0
988  1700030_y32     0
989  1700030_y33     0

[990 rows x 2 columns]

In [11]:
df = pd.DataFrame(predictions)

In [12]:
output=df.to_csv('output.csv')

In [13]:
op=pd.read_csv('output.csv')
op.head(50)

    Unnamed: 0     0  1  2  3  4  5  6  7  ...  25  26  27  28  29  30  31  32  33
0            0  4455  0  0  0  0  0  0  0  ...   0   1   0   0   0   0   0   0   0
1            1  2167  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
2            2  3394  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
3            3   212  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
4            4   777  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
5            5  3110  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
6            6  2012  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
7            7  1128  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
8            8  4736  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
9            9  2470  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
10          10  2274  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
11          11   799  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
12          12  3119  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
13          13  4447  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
14          14  4745  0  0  0  0  0  1  0  ...   0   0   0   0   0   0   0   0   0
15          15  1913  0  0  0  0  0  0  0  ...   0   0   0   0   1   0   0   0   0
16          16  2488  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
17          17  3409  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
18          18  3898  0  0  0  0  0  1  0  ...   0   0   0   0   0   0   0   0   0
19          19  3388  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   1   0
20          20  4890  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
21          21  4611  0  0  0  0  0  0  1  ...   0   0   0   0   0   0   0   0   0
22          22  4585  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
23          23  4672  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
24          24  4361  0  0  0  0  0  0  1  ...   0   0   0   0   0   0   0   0   0
25          25  1473  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
26          26   786  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
27          27  3388  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   1   0
28          28  3384  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
29          29   893  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
30          30  4242  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0
31          31  3524  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0
32          32  1150  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
33          33   378  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
34          34  2800  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
35          35  1209  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
36          36   866  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
37          37  4382  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0
38          38  4687  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
39          39   132  0  0  0  0  0  0  0  ...   0   0   0   0   0   1   0   0   0
40          40  1116  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
41          41  3527  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
42          42  2891  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
43          43  2641  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
44          44  2191  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
45          45  4504  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   1   0
46          46  4474  0  0  0  0  0  0  0  ...   0   0   0   0   1   0   0   0   0
47          47  2699  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1
48          48  4938  0  0  0  0  0  1  0  ...   0   0   0   0   0   0   1   0   0
49          49  4069  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1

[50 rows x 35 columns]

In [14]:
y_train.head()

        id  y1  y2  y3  y4  y5  y6  y7  ...  y26  y27  y28  y29  y30  y31  y32  y33
3186  3187   0   0   0   0   0   1   0  ...    0    0    0    0    0    0    0    0
632    633   1   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    0
577    578   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
2406  2407   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
4686  4687   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1

[5 rows x 34 columns]

In [15]:
y_train.columns.values

array(['id', 'y1', 'y2', 'y3', 'y4', 'y5', 'y6', 'y7', 'y8', 'y9', 'y10',
       'y11', 'y12', 'y13', 'y14', 'y15', 'y16', 'y17', 'y18', 'y19',
       'y20', 'y21', 'y22', 'y23', 'y24', 'y25', 'y26', 'y27', 'y28',
       'y29', 'y30', 'y31', 'y32', 'y33'], dtype=object)

In [16]:

print(f"Train labels:\n{y_train}")
print(f"Test labels:\n{y_test}")

Train labels:
        id  y1  y2  y3  y4  y5  y6  y7  ...  y26  y27  y28  y29  y30  y31  y32  y33
3186  3187   0   0   0   0   0   1   0  ...    0    0    0    0    0    0    0    0
632    633   1   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    0
577    578   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
2406  2407   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
4686  4687   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
...    ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...
2895  2896   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
2763  2764   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
905    906   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
3980  3981   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
235    236   0   0   0   0   0   0   1  ...    0    0    0    0    0    0    0    0

[3750 rows x 34 columns]
Test labels:
        id  y1  y2  y3  y4  y5  y6  y7  ...  y26  y27  y28  y29  y30  y31  y32  y33
2764  2765   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
4767  4768   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
3814  3815   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
3499  3500   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
2735  2736   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
...    ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...
3015  3016   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    0
1891  1892   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    0
2773  2774   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
3803  3804   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1
3301  3302   0   0   0   0   0   0   0  ...    0    0    0    0    0    0    0    1

[1250 rows x 34 columns]

In [17]:
y_train = y_train.mask(y_train.eq(1), y_train.columns.to_series(), axis=1)
y_train

        id  y1 y2 y3 y4  y5  y6  y7 y8  ... y25 y26 y27 y28 y29  y30 y31 y32  y33
3186  3187   0  0  0  0   0  y6   0  0  ...   0   0   0   0   0    0   0   0    0
632    633  y1  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0    0
577    578   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
2406  2407   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
4686  4687   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
...    ...  .. .. .. ..  ..  ..  .. ..  ...  ..  ..  ..  ..  ..  ...  ..  ..  ...
2895  2896   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
2763  2764   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
905    906   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
3980  3981   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
235    236   0  0  0  0   0   0  y7  0  ...   0   0   0   0   0    0   0   0    0

[3750 rows x 34 columns]

In [18]:
y_train = y_train[(y_train.T != 0).any()]
y_train

        id  y1 y2 y3 y4  y5  y6  y7 y8  ... y25 y26 y27 y28 y29  y30 y31 y32  y33
3186  3187   0  0  0  0   0  y6   0  0  ...   0   0   0   0   0    0   0   0    0
632    633  y1  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0    0
577    578   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
2406  2407   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
4686  4687   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
...    ...  .. .. .. ..  ..  ..  .. ..  ...  ..  ..  ..  ..  ..  ...  ..  ..  ...
2895  2896   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
2763  2764   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
905    906   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
3980  3981   0  0  0  0   0   0   0  0  ...   0   0   0   0   0    0   0   0  y33
235    236   0  0  0  0   0   0  y7  0  ...   0   0   0   0   0    0   0   0    0

[3750 rows x 34 columns]

In [19]:
y_train.loc[:, (y_train == 0).any(axis=0)]

      y1 y2 y3 y4  y5  y6  y7 y8 y9  ... y25 y26 y27 y28  y29 y30 y31 y32  y33
3186   0  0  0  0   0  y6   0  0  0  ...   0   0   0   0    0   0   0   0    0
632   y1  0  0  0   0   0   0  0  0  ...   0   0   0   0    0   0   0   0    0
577    0  0  0  0   0   0   0  0  0  ...   0   0   0   0    0   0   0   0  y33
2406   0  0  0  0   0   0   0  0  0  ...   0   0   0   0    0   0   0   0  y33
4686   0  0  0  0   0   0   0  0  0  ...   0   0   0   0    0   0   0   0  y33
...   .. .. .. ..  ..  ..  .. .. ..  ...  ..  ..  ..  ..  ...  ..  ..  ..  ...
2895   0  0  0  0   0   0   0  0  0  ...   0   0   0   0    0   0   0   0  y33
2763   0  0  0  0   0   0   0  0  0  ...   0   0   0   0    0   0   0   0  y33
905    0  0  0  0   0   0   0  0  0  ...   0   0   0   0    0   0   0   0  y33
3980   0  0  0  0   0   0   0  0  0  ...   0   0   0   0    0   0   0   0  y33
235    0  0  0  0   0   0  y7  0  0  ...   0   0   0   0    0   0   0   0    0

[3750 rows x 33 columns]

In [20]:
test= pd.read_csv('test.csv')
test

      1698001   NO NO.1  ... 0.31 0.0896860986547085  0.193343898573693.1
0     1698002   NO   NO  ...    5           0.945032             0.471318
1     1698003   NO   NO  ...    8           0.557175             0.693587
2     1698004  NaN  NaN  ...    0           0.870538             0.405822
3     1698005   NO   NO  ...    2           0.224729             0.870909
4     1698006   NO   NO  ...    6           0.536996             0.223278
...       ...  ...  ...  ...  ...                ...                  ...
1994  1699996   NO   NO  ...    2           0.198257             0.155724
1995  1699997   NO   NO  ...    0           0.582479             0.778864
1996  1699998   NO   NO  ...    5           0.930588             0.201591
1997  1699999   NO   NO  ...    2           0.256471             0.938182
1998  1700000   NO   NO  ...    0           0.190807             0.416506

[1999 rows x 146 columns]

In [21]:
y_train = y_train.mask(y_train.eq(0), y_train.columns.to_series(), axis=0)
y_train.head(50)

        id   y1   y2   y3   y4   y5   y6  ...  y27  y28  y29  y30  y31  y32  y33
3186  3187  NaN  NaN  NaN  NaN  NaN   y6  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
632    633   y1  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
577    578  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
2406  2407  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
4686  4687  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
787    788  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  y30  y31  NaN  NaN
1080  1081  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
4254  4255  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
233    234  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
4109  4110  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
1938  1939  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  y30  NaN  NaN  NaN
2917  2918  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  y28  NaN  NaN  NaN  NaN  NaN
2233  2234  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  y29  NaN  NaN  y32  NaN
4610  4611  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4865  4866  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
784    785  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4427  4428  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
3227  3228  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
1385  1386  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
785    786  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
524    525  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
714    715  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  y29  NaN  NaN  NaN  NaN
4524  4525  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  y30  NaN  NaN  NaN
2738  2739  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4236  4237  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1740  1741  NaN  NaN  NaN  NaN  NaN   y6  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3998  3999  NaN  NaN  NaN  NaN  NaN   y6  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4067  4068  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
4413  4414  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
857    858  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4461  4462  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
292    293  NaN  NaN  NaN  NaN  NaN   y6  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2159  2160  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
561    562  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
4418  4419  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
93      94  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
661    662  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
3414  3415  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1061  1062  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
2374  2375   y1  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4933  4934  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
3908  3909  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2689  2690  NaN  NaN  NaN   y4  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
657    658  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
3527  3528  NaN  NaN   y3  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3782  3783  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
4757  4758  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
3665  3666  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  y32  NaN
4393  4394  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
389    390  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33

[50 rows x 34 columns]

In [22]:
y_train.dropna()     #drop all rows that have any NaN values
y_train.dropna(how='all')

        id   y1   y2   y3   y4   y5   y6  ...  y27  y28  y29  y30  y31  y32  y33
3186  3187  NaN  NaN  NaN  NaN  NaN   y6  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
632    633   y1  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
577    578  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
2406  2407  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
4686  4687  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2895  2896  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
2763  2764  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
905    906  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
3980  3981  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  y33
235    236  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[3750 rows x 34 columns]

In [23]:
s = (y_train.replace({ 0: '0'})
     .iloc[:, 1:]
     .sum(1))

y_train['pred'] = np.where(s.groupby(y_train['id']).rank(ascending=False).eq(1),1,0)
y_train

        id   y1   y2   y3   y4   y5   y6  ...  y28  y29  y30  y31  y32  y33 pred
3186  3187  NaN  NaN  NaN  NaN  NaN   y6  ...  NaN  NaN  NaN  NaN  NaN  NaN    1
632    633   y1  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN    1
577    578  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  y33    1
2406  2407  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  y33    1
4686  4687  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  y33    1
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2895  2896  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  y33    1
2763  2764  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  y33    1
905    906  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  y33    1
3980  3981  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  y33    1
235    236  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN    1

[3750 rows x 35 columns]

In [24]:
data = y_train.fillna('')
data

        id  y1 y2 y3 y4 y5  y6  y7 y8  ... y26 y27 y28 y29 y30 y31 y32  y33 pred
3186  3187                  y6         ...                                     1
632    633  y1                         ...                                     1
577    578                             ...                              y33    1
2406  2407                             ...                              y33    1
4686  4687                             ...                              y33    1
...    ...  .. .. .. .. ..  ..  .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ...  ...
2895  2896                             ...                              y33    1
2763  2764                             ...                              y33    1
905    906                             ...                              y33    1
3980  3981                             ...                              y33    1
235    236                      y7     ...                                     1

[3750 rows x 35 columns]

In [25]:
data

        id  y1 y2 y3 y4 y5  y6  y7 y8  ... y26 y27 y28 y29 y30 y31 y32  y33 pred
3186  3187                  y6         ...                                     1
632    633  y1                         ...                                     1
577    578                             ...                              y33    1
2406  2407                             ...                              y33    1
4686  4687                             ...                              y33    1
...    ...  .. .. .. .. ..  ..  .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ...  ...
2895  2896                             ...                              y33    1
2763  2764                             ...                              y33    1
905    906                             ...                              y33    1
3980  3981                             ...                              y33    1
235    236                      y7     ...                                     1

[3750 rows x 35 columns]

In [26]:
data1=data.to_csv('Sample_output.csv')
data1=pd.read_csv('Sample_output.csv')
data1

      Unnamed: 0    id   y1   y2   y3   y4  ...  y29  y30  y31  y32  y33 pred
0           3186  3187  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN    1
1            632   633   y1  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN    1
2            577   578  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  y33    1
3           2406  2407  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  y33    1
4           4686  4687  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  y33    1
...          ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
3745        2895  2896  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  y33    1
3746        2763  2764  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  y33    1
3747         905   906  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  y33    1
3748        3980  3981  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  y33    1
3749         235   236  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN    1

[3750 rows x 36 columns]

In [27]:
p=y_train.apply(lambda r: r[r.last_valid_index()], axis=1)

In [28]:
for id in y_train.index:
 row = y_train.loc[id,]
for i in range(0,len(row)):
    if (~pd.isnull(row[i])):
        y_train.loc[id,'pred'] = row.index[i]
        break

In [29]:
y_train.apply(lambda y_train: y_train[y_train.first_valid_index()], axis=1)

3186    3187
632      633
577      578
2406    2407
4686    4687
        ...
2895    2896
2763    2764
905      906
3980    3981
235      236
Length: 3750, dtype: object

In [30]:
output_sample=y_train.apply(lambda y_train: y_train[['id','pred']],axis=1)
output_sample.head(50)

        id pred
3186  3187    1
632    633    1
577    578    1
2406  2407    1
4686  4687    1
787    788    1
1080  1081    1
4254  4255    1
233    234    1
4109  4110    1
1938  1939    1
2917  2918    1
2233  2234    1
4610  4611    1
4865  4866    1
784    785    1
4427  4428    1
3227  3228    1
1385  1386    1
785    786    1
524    525    1
714    715    1
4524  4525    1
2738  2739    1
4236  4237    1
1740  1741    1
3998  3999    1
4067  4068    1
4413  4414    1
857    858    1
4461  4462    1
292    293    1
2159  2160    1
561    562    1
4418  4419    1
93      94    1
661    662    1
3414  3415    1
1061  1062    1
2374  2375    1
4933  4934    1
3908  3909    1
2689  2690    1
657    658    1
3527  3528    1
3782  3783    1
4757  4758    1
3665  3666    1
4393  4394    1
389    390    1